version: 1.0.{build}

image: ubuntu

build_script:
  - dotnet build

environment:
  NUGET_API_KEY:
    secure: M8kSq/XBFS6NriAu52f+ISNKzkmJVLjjOJw3P6+ShNaqnHcte4rAF4n5ijfFZ1Wa

deploy_script:
  - bash scripts\deploy.sh

branches:
  only:
    - master