version: 1.0.{build}

image: ubuntu

build_script:
  - dotnet build

environment:
  NUGET_API_KEY:
    secure: M8kSq/XBFS6NriAu52f+ISNKzkmJVLjjOJw3P6+ShNaqnHcte4rAF4n5ijfFZ1Wa

deploy_script:
  - bash scripts/deploy.sh src/Cake.PickAndRoll/Cake.PickAndRoll.csproj

artifacts:
  - path: '*.nupkg'

after_deploy:
  - ps: Get-ChildItem *.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
